;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        kill-region
        mc/skip-next-like-this
        paredit-forward-delete
        paredit-forward-kill-word
        selected-off
        ))

(setq mc/cmds-to-run-once
      '(
        indent-region
        paredit-backslash
        paredit-close-square
        paredit-newline
        paredit-open-square
        smex
        ))
